steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - HelloHTTP
      - --region=us-central1
      - --source .
      - --trigger-http
      - --runtime go119
